from enum import StrEnum


class SessionState(StrEnum):
    IDLE = "IDLE"
    WAKE_DETECTED = "WAKE_DETECTED"
    LISTENING = "LISTENING"
    THINKING = "THINKING"
    SPEAKING = "SPEAKING"
    WAITING_FOR_NEXT_TURN = "WAITING_FOR_NEXT_TURN"
    CONFIRMING_END = "CONFIRMING_END"
    CLOSING = "CLOSING"
    PROACTIVE_CANDIDATE = "PROACTIVE_CANDIDATE"
    PROACTIVE_PERMISSION_CHECK = "PROACTIVE_PERMISSION_CHECK"
